FROM node:18-alpine as build

# Клонируем репозиторий с проектом
ADD https://github.com/KyrylStudy/MasterProject.git /app

# Переходим в рабочую директорию
WORKDIR /app/frontend

# Копируем только package.json и package-lock.json для кэширования зависимостей
COPY package*.json ./

# Устанавливаем зависимости проекта (только для фронтенда)
RUN npm ci

# Собираем проект с помощью локальной версии Angular CLI
RUN npx ng build --configuration=production --project=frontend

FROM node:18-alpine as worker

# Копируем собранные файлы из первого образа
COPY --from=build /app/frontend /app

# Запускаем приложение на сервере с помощью npx для вызова Angular CLI
WORKDIR /app
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
