version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    #environment:
    #  - DB_HOST=db
    #  - DB_USER=root
    #  - DB_PASSWORD=369415Vip*
    #  - DB_NAME=autotech_agil
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autotech_agil
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 20s
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Persist database data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local